# Generated by Django 4.1.5 on 2023-02-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_name_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='C:\\Users\\Surface\\PycharmProjects\\medical_center\\media/photos'),
        ),
    ]
