# Generated by Django 4.1.5 on 2023-02-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='C:\\Users\\Surface\\PycharmProjects\\medical_center\\media//media/photos'),
        ),
    ]
